// packages/react/src/components/Tooltip/index.tsx
import { tooltip } from "@toshusai/cmpui-core";
import React, {
  CSSProperties,
  isValidElement,
  useEffect,
  useId,
  useLayoutEffect,
  useRef,
  useState,
} from "react";
import { createPortal } from "react-dom";
import { Side } from "@floating-ui/dom";

export type TooltipProps = {
  children: React.ReactNode;
  content: React.ReactNode;
  forceShow?: boolean;
  side?: Side;
  delay?: number;
  group?: string;
  groupDelay?: number;
};

const defaultGroup = "cmpuiTooltip";

export const Tooltip = (rawProps: TooltipProps) => {
  const props = {
    group: defaultGroup,
    groupDelay: 200,
    delay: 300,
    ...rawProps,
  } as const;
  const [show, setShow] = useState(false);

  const [style, setStyle] = useState<CSSProperties>({
    display: "none",
    position: "fixed",
    top: "0",
    left: "0",
  });

  const childRef = useRef<HTMLDivElement>(null);

  const id = useId();

  const setData = (value?: string) => {
    const key = props.group;
    if (value === undefined) {
      delete document.body.dataset[key];
      return;
    }
    document.body.dataset[key] = value;
  };
  const getData = () => {
    return document.body.dataset[props.group ?? defaultGroup];
  };

  useEffect(() => {
    if (!show) {
      setShow(false);
      setTimeout(() => {
        if (id === getData()) {
          setData(undefined);
        }
      }, props.groupDelay);
    }
  }, [show]);

  const timeoutRef = useRef<number | null>(null);
  const newChildren = React.Children.map(props.children, (child) => {
    if (isValidElement(child)) {
      return React.cloneElement(child, {
        // FIXME: This might not work with all elements
        // eslint-disable-next-line @typescript-eslint/ban-ts-comment
        // @ts-ignore
        onPointerEnter: () => {
          if (timeoutRef.current) clearTimeout(timeoutRef.current);
          if (getData()) {
            setData(id);
            setShow(true);
          } else {
            timeoutRef.current = window.setTimeout(() => {
              setShow(true);
              setData(id);
            }, props.delay);
          }
        },
        onPointerLeave: () => {
          if (timeoutRef.current) {
            clearTimeout(timeoutRef.current);
          }
          setShow(false);
        },
        ref: childRef,
        ["aria-describedby"]: id,
      });
    }
    return child;
  });
  const tooltipRef = useRef<HTMLDivElement>(null);
  const arrowRef = useRef<SVGSVGElement>(null);

  useLayoutEffect(() => {
    if (!tooltipRef.current || !arrowRef.current) return;
    if (!childRef.current) return;
    const { cleanUp, open } = tooltip(
      tooltipRef.current,
      childRef.current,
      arrowRef.current,
      () => {},
      (pos) => {
        setStyle((prev) => {
          const newStyle = { ...prev };
          if (pos.left !== undefined && pos.top !== undefined) {
            newStyle.transform = `translate(${pos.left}px, ${pos.top}px)`;
          }
          if (pos.maxWidth !== undefined) {
            newStyle.maxWidth = `${pos.maxWidth}px`;
          }
          if (pos.maxHeight !== undefined) {
            newStyle.maxHeight = `${pos.maxHeight}px`;
          }
          newStyle.display = undefined;
          newStyle.opacity = undefined;

          return newStyle;
        });
        if (!arrowRef.current) return;

        arrowRef.current.style.left =
          pos.arrow?.x != null ? `${pos.arrow.x}px` : "";
        arrowRef.current.style.top =
          pos.arrow?.y != null ? `${-pos.arrow.y}px` : "";

        if (pos.placement === "bottom") {
          arrowRef.current.style.transform = "rotate(180deg)";
          arrowRef.current.style.transformOrigin = "top";
          arrowRef.current.style.top = "0";
          arrowRef.current.style.bottom = "";
        } else if (pos.placement === "top") {
          arrowRef.current.style.transform = "rotate(0deg)";
          arrowRef.current.style.transformOrigin = "bottom";
          arrowRef.current.style.top = "";
          arrowRef.current.style.bottom = "-5px";
        } else if (pos.placement === "left") {
          arrowRef.current.style.transform = "rotate(-90deg)";
          arrowRef.current.style.transformOrigin = "right";
          arrowRef.current.style.top = "";
        } else if (pos.placement === "right") {
          arrowRef.current.style.transform = "rotate(90deg)";
          arrowRef.current.style.transformOrigin = "left";
          arrowRef.current.style.top = "";
          arrowRef.current.style.left = "-2px";
        }
      },
      {
        placement: props.side ?? "top",
      },
    );

    if (show || props.forceShow) {
      // Hack to make sure the tooltip is visible
      setStyle((prev) => {
        return {
          ...prev,
          display: undefined,
          opacity: 0,
        };
      });
      requestAnimationFrame(() => {
        open();
      });
    }

    return () => {
      cleanUp();
    };
  }, [show, props.side]);

  return (
    <>
      {newChildren}
      {(show || props.forceShow) &&
        createPortal(
          <div
            ref={tooltipRef}
            className="cmpui_tooltip__root"
            role="tooltip"
            style={style}
            id={id}
          >
            {props.content}
            <svg
              ref={arrowRef}
              className="cmpui_tooltip__arrow"
              style={{ position: "absolute" }}
              width="10"
              height="5"
              viewBox="0 0 30 10"
              preserveAspectRatio="none"
            >
              <polygon points="0,0 30,0 15,10" />
            </svg>
          </div>,
          document.body,
        )}
    </>
  );
};

// packages/vue/src/components/Tooltip/Tooltip.vue
<script setup lang="ts">
import {
  ComponentPublicInstance,
  computed,
  CSSProperties,
  inject,
  onMounted,
  ref,
  useSlots,
  watch,
} from "vue";
import { tooltip } from "../../../../core/src/tooltip/tooltip";
import { useId } from "../../lib/useId";
import { isValidVNode, TOAST_PROVIDER_KEY, TooltipProvide } from "./lib";

const props = withDefaults(
  defineProps<{
    text: string;
    forceShow?: boolean;
    delay?: number;
  }>(),
  {
    forceShow: false,
    delay: 300,
  },
);

const style = ref<CSSProperties>({
  display: "none",
  position: "fixed",
  top: "0",
  left: "0",
});

const provider = inject<TooltipProvide | undefined>(
  TOAST_PROVIDER_KEY,
  undefined,
);

const slots = useSlots();

onMounted(() => {
  const children = slots.default?.().filter(isValidVNode) ?? [];
  if (children.length === 0) return;
  if (children.length > 1) {
    console.error("Tooltip can only have one child");
    return;
  }
});

const slotRef = ref<HTMLElement | ComponentPublicInstance | null>(null);
const tooltipRef = ref<HTMLElement | null>(null);
const arrowRef = ref<HTMLElement | null>(null);

const show = ref(false);

const slotElement = computed(() => {
  let el = slotRef.value;
  if (!el) return;
  if (!(el instanceof HTMLElement)) {
    el = el.$el;
    if (!(el instanceof HTMLElement)) return;
  }
  return el;
});

let i: ReturnType<typeof setTimeout> | undefined;
const handleMouseEnter = () => {
  if (provider?.show.value === true) {
    show.value = true;
    return;
  }
  i = setTimeout(() => {
    show.value = true;
  }, props.delay);
};

const handleMouseLeave = () => {
  clearTimeout(i);
  show.value = false;
};

watch(
  () => show.value,
  (show) => {
    if (provider) {
      provider.setShow(show);
    }
  },
);

watch(
  () => [slotRef.value, tooltipRef.value, arrowRef.value],
  () => {
    if (!slotRef.value) return;
    if (!tooltipRef.value) return;
    if (!slotElement.value) return;
    if (!arrowRef.value) return;
    const { cleanUp, open } = tooltip(
      tooltipRef.value,
      slotElement.value,
      arrowRef.value,
      () => {
        show.value = false;
      },
      (pos) => {
        show.value = true;

        if (pos.left !== undefined && pos.top !== undefined) {
          style.value.transform = `translate(${pos.left}px, ${pos.top}px)`;
        }
        if (pos.maxWidth !== undefined) {
          style.value.maxWidth = `${pos.maxWidth}px`;
        }
        if (pos.maxHeight !== undefined) {
          style.value.maxHeight = `${pos.maxHeight}px`;
        }
        style.value.display = "";

        if (!arrowRef.value) return;

        arrowRef.value.style.left =
          pos.arrow?.x != null ? `${pos.arrow.x}px` : "";
        arrowRef.value.style.top =
          pos.arrow?.y != null ? `${-pos.arrow.y}px` : "";

        if (pos.placement === "bottom") {
          arrowRef.value.style.transform = "rotate(180deg)";
          arrowRef.value.style.transformOrigin = "top";
          arrowRef.value.style.top = "0";
          arrowRef.value.style.bottom = "";
        } else if (pos.placement === "top") {
          arrowRef.value.style.transform = "rotate(0deg)";
          arrowRef.value.style.transformOrigin = "bottom";
          arrowRef.value.style.top = "";
          arrowRef.value.style.bottom = "-5px";
        }
      },
    );

    let stop = () => {};
    const handleOpenChange = (show: boolean) => {
      if (show) {
        open();
      } else {
        cleanUp();
        style.value.display = "none";
      }
      stop();
    };

    handleOpenChange(show.value || props.forceShow);
    stop = watch(
      () => [show.value, props.forceShow],
      ([show, forceShow]) => handleOpenChange(show || forceShow),
    );
  },
);

watch(
  () => props.forceShow,
  (forceShow) => {
    show.value = forceShow;
  },
);

const id = useId();
</script>

<template>
  <component
    :is="slots.default?.()[0]"
    ref="slotRef"
    :aria-describedby="show || forceShow ? id : undefined"
    @pointerenter="handleMouseEnter"
    @pointerleave="handleMouseLeave"
  />
  <div
    v-if="show || forceShow"
    :id="id"
    ref="tooltipRef"
    class="cmpui_tooltip__root"
    role="tooltip"
    v-bind="$attrs"
    :style="style"
  >
    {{ text }}
    <svg
      ref="arrowRef"
      class="cmpui_tooltip__arrow"
      style="position: absolute"
      width="10"
      height="5"
      viewBox="0 0 30 10"
      preserveAspectRatio="none"
    >
      <polygon points="0,0 30,0 15,10" />
    </svg>
  </div>
</template>
