// packages/vue/src/components/Popover/Popover.vue
<script setup lang="ts">
import { CSSProperties, onMounted, onUnmounted, ref, watch } from "vue";
import { setPopover } from "../../../../core/src/popover/setPopover";
import { useId } from "../../lib/useId";
import { Placement } from "@floating-ui/dom";
import { lockScroll } from "@toshusai/cmpui-core";

const divRef = ref<HTMLElement | null>(null);

const props = defineProps<{
  disabledTriggerClickClose?: boolean;
  id?: string;
  placement?: Placement;
  show: boolean;
  trigger: HTMLElement | null;
}>();

const emit = defineEmits<{
  (_e: "close"): void;
}>();

const style = ref<CSSProperties>({
  display: "none",
  position: "fixed",
  top: "0",
  left: "0",
});

let componentCleanUp = () => {};

watch(
  () => [props.trigger, divRef.value, props.show],
  () => {
    if (!props.trigger) return;
    if (!divRef.value) return;
    const { cleanUp, open } = setPopover(
      divRef.value,
      props.trigger,
      () => {
        emit("close");
      },
      (pos) => {
        if (pos.left !== undefined && pos.top !== undefined) {
          style.value.transform = `translate(${pos.left}px, ${pos.top}px)`;
        }
        if (pos.maxWidth !== undefined) {
          style.value.maxWidth = `${pos.maxWidth}px`;
        }
        if (pos.maxHeight !== undefined) {
          style.value.maxHeight = `${pos.maxHeight}px`;
        }
        style.value.display = "";
      },
      {
        disabledTriggerClickClose: props.disabledTriggerClickClose,
        placement: props.placement,
      },
    );

    const handleOpenChange = (show: boolean) => {
      if (show) {
        open();
      } else {
        cleanUp();
        style.value.display = "none";
      }
    };

    handleOpenChange(props.show);

    watch(() => props.show, handleOpenChange);

    componentCleanUp = cleanUp;
  },
);

let cleanUp = () => {};
onMounted(() => {
  if (props.show) {
    const cleanUpLockScroll = lockScroll();
    cleanUp = () => {
      cleanUpLockScroll();
    };
  } else {
    cleanUp();
  }
});

onUnmounted(() => {
  componentCleanUp();
  cleanUp();
});

const id = useId(props.id);
</script>

<template>
  <Teleport to="body">
    <div
      :id="id"
      ref="divRef"
      class="cmpui_float-box__root"
      tabindex="-1"
      v-bind="$attrs"
      :style="style"
    >
      <slot></slot>
    </div>
  </Teleport>
</template>

// packages/react/src/components/Popover/index.tsx
import { createPortal } from "react-dom";
import {
  CSSProperties,
  memo,
  RefObject,
  useEffect,
  useRef,
  useState,
} from "react";
import {
  lockScroll,
  Option,
  setPopover,
  focusTrap as cmpUiFocusTrap,
} from "@toshusai/cmpui-core";

import { FloatBox } from "../FloatBox";

export type PopoverProps = {
  children: React.ReactNode;
  trigger: RefObject<HTMLElement>;
  isOpen?: boolean;
  onClose?: () => void;
  scrollLock?: boolean;
  focusTrap?: boolean;
} & Option;

export const MemoPopover = memo(Popover);

export function Popover(props: PopoverProps) {
  const [style, setStyle] = useState<Partial<CSSProperties>>({
    display: "none",
    position: "fixed",
    top: "0",
    left: "0",
  });

  useEffect(() => {
    if (!ref.current) return;
    if (!props.trigger.current) return;
    const { cleanUp, open } = setPopover(
      ref.current,
      props.trigger.current,
      () => {},
      (pos) => {
        setStyle((prev) => {
          const newStyle = { ...prev };
          if (pos.left !== undefined && pos.top !== undefined) {
            newStyle.transform = `translate(${pos.left}px, ${pos.top}px)`;
          }
          if (pos.maxWidth !== undefined) {
            newStyle.maxWidth = `${pos.maxWidth}px`;
          }
          if (pos.maxHeight !== undefined) {
            newStyle.maxHeight = `${pos.maxHeight}px`;
            ref.current!.style.maxHeight = `${pos.maxHeight}px`;
          }
          newStyle.display = "";

          return newStyle;
        });
      },
      {
        ...props,
      },
      () => {
        props.onClose?.();
      },
    );

    open();

    const cleanUpScrollLock =
      (props.scrollLock ?? true) ? lockScroll() : () => {};
    const focusTrapCleanUp = props.focusTrap
      ? cmpUiFocusTrap(ref.current)
      : () => {};

    return () => {
      cleanUpScrollLock();
      focusTrapCleanUp();
      cleanUp();
    };
  }, [props.trigger.current, props.onClose, props.isOpen]);

  const ref = useRef<HTMLDivElement>(null);

  if (!props.isOpen) {
    return null;
  }
  return createPortal(
    <FloatBox
      ref={ref}
      className="cmpui_popover__root"
      tabIndex={-1}
      style={style}
    >
      {props.children}
    </FloatBox>,
    document.body,
  );
}
