// packages/vue/src/components/MenuList/MenuList.vue
<script setup lang="ts">
import { onMounted, onUnmounted, ref } from "vue";
import { useKeyboardNavigation } from "../../../../core/src/menuItem";

const props = withDefaults(
  defineProps<{
    defaultValue?: string;
    autoFocus?: boolean;
  }>(),
  {
    autoFocus: true,
    defaultValue: undefined,
  },
);

const emit = defineEmits<{
  (_e: "select", v: string): void;
}>();

const el = ref<HTMLDivElement | null>(null);

let cleanup = () => {};

onMounted(() => {
  if (!el.value) return;
  if (props.autoFocus) {
    setTimeout(() => {
      el.value?.focus();
    }, 0);
  }
  cleanup = useKeyboardNavigation(
    el.value,
    (value) => {
      emit("select", value);
    },
    {
      defaultValue: props.defaultValue,
    },
  );
});

onUnmounted(() => {
  cleanup();
});
</script>

<template>
  <div ref="el" class="cmpui_menu-list" role="listbox" tabindex="-1">
    <slot></slot>
  </div>
</template>

// packages/react/src/components/MenuList/MenuList.tsx
import { useKeyboardNavigation } from "@toshusai/cmpui-core";
import { useEffect, useRef } from "react";

export function MenuList({
  defaultValue,
  autoFocus,
  onSelect,
  children,
  ...props
}: {
  defaultValue?: string;
  autoFocus?: boolean;
  onSelect?: (value: string) => void;
  children: React.ReactNode;
} & Omit<React.HTMLAttributes<HTMLDivElement>, "onSelect" | "defaultValue">) {
  const el = useRef<HTMLDivElement>(null);

  useEffect(() => {
    if (!(autoFocus === false)) {
      setTimeout(() => {
        el.current?.focus();
      }, 0);
    }
  }, [autoFocus]);
  useEffect(() => {
    const cleanup = useKeyboardNavigation(
      el.current!,
      (value) => {
        onSelect?.(value);
      },
      {
        defaultValue: defaultValue,
      },
    );

    return () => {
      cleanup();
    };
  }, [defaultValue, onSelect]);

  return (
    <div
      ref={el}
      className="cmpui_menu-list"
      role="listbox"
      tabIndex={-1}
      {...props}
    >
      {children}
    </div>
  );
}
