// packages/vue/src/components/Checkbox/Checkbox.vue
<script setup lang="ts">
import { useId } from "../../lib/useId";

withDefaults(
  defineProps<{
    label?: string;
    checked?: boolean;
    disabled?: boolean;
    onChange?: (checked: boolean) => void;
  }>(),
  {
    checked: false,
    disabled: false,
    label: undefined,
    onChange: undefined,
  },
);

const id = useId();
</script>

<template>
  <div class="cmpui_checkbox__root" :aria-disabled="disabled">
    <input
      :id="id"
      type="checkbox"
      class="cmpui_checkbox__input"
      :disabled="disabled"
      :checked="checked"
      :on-change="checked"
      v-bind="$attrs"
    />
    <label v-if="$slots.default" class="cmpui_checkbox__label" :for="id">
      <slot></slot>
    </label>
  </div>
</template>

// src/components/Checkbox/index.tsx
import { useCallback } from "react";
import { CheckSVG } from "./CheckSVG";

import "./index.css";

export type CheckboxProps = {
  label?: React.ReactNode;
  checked?: boolean;
  onChange?: (checked: boolean) => void;
  disabled?: boolean;
  id?: string;
};

export function Checkbox(props: CheckboxProps) {
  const handleChange = useCallback(
    (e: React.ChangeEvent<HTMLInputElement>) => {
      props.onChange?.(e.target.checked);
    },
    [props.onChange],
  );
  return (
    <div className="cmpui_checkbox__root" aria-disabled={props.disabled}>
      <div className="cmpui_checkbox__box">
        <input
          type="checkbox"
          className="cmpui_checkbox__input"
          id={props.id}
          disabled={props.disabled}
          checked={props.checked}
          onChange={handleChange}
        />
        <div className="cmpui_checkbox__indicator" data-checked={props.checked}>
          <CheckSVG />
        </div>
      </div>
      {props.label && (
        <label className="cmpui_checkbox__label" htmlFor={props.id}>
          {props.label}
        </label>
      )}
    </div>
  );
}
