// packages/react/src/components/Modal/index.tsx
import React, { useEffect, useRef } from "react";
import { createPortal } from "react-dom";
import { ariaHiddenOthers, focusTrap, lockScroll } from "@toshusai/cmpui-core";

import { classNames } from "../../utils/classNames";
import { FloatBox } from "../FloatBox";
import { IconButton } from "../IconButton";

export type ModalProps = {
  children: React.ReactNode;
  container?: HTMLElement | null;
  hideCloseButton?: boolean;
  onClose?: () => void;
  open?: boolean;
  title: string;
  trigger?: React.ReactNode;
  className?: string;
};

export function Modal(props: ModalProps) {
  const ref = useRef<HTMLDivElement>(null);

  useEffect(() => {
    const el = ref.current;
    if (!el) return;
    if (!props.open) return;
    const cleanUpFocusTrap = focusTrap(el);
    const cleanUpLockScroll = lockScroll();
    const cleanUpAriaHiddenOthers = ariaHiddenOthers(el);
    return () => {
      cleanUpFocusTrap();
      cleanUpLockScroll();
      cleanUpAriaHiddenOthers();
    };
  }, [props.open]);

  if (!props.open) return null;

  return createPortal(
    <div ref={ref} className="cmpui_modal__overlay">
      <FloatBox className={classNames("cmpui_modal__root", props.className)}>
        <div className="cmpui_modal__header">
          <div className="cmpui_modal__title">{props.title}</div>
          <IconButton
            className="cmpui_modal__close-button"
            size="S"
            onClick={props.onClose}
          ></IconButton>
        </div>
        <hr className="cmpui_modal__divider" />
        <div>{props.children}</div>
      </FloatBox>
    </div>,
    document.body,
  );
}

// packages/vue/src/components/Modal/Modal.vue
<script setup lang="ts">
import { ref, watch } from "vue";
import IconButton from "../IconButton/IconButton.vue";
import { useId } from "../../lib/useId";
import { ariaHiddenOthers, focusTrap, lockScroll } from "@toshusai/cmpui-core";

const el = ref<HTMLElement | null>(null);

const props = defineProps<{
  show: boolean;
  title: string;
}>();

const emit = defineEmits<{
  (_e: "close"): void;
}>();

let cleanUp = () => {};

watch(
  () => el.value,
  (el) => {
    if (el) {
      const cleanUpFocusTrap = focusTrap(el);
      const cleanUpLockScroll = lockScroll();
      const cleanUpAriaHiddenOthers = ariaHiddenOthers(el);
      cleanUp = () => {
        cleanUpFocusTrap();
        cleanUpLockScroll();
        cleanUpAriaHiddenOthers();
      };
    }
  },
);

watch(
  () => props.show,
  (show) => {
    if (!show) cleanUp();
  },
);
const id = useId();
</script>

<template>
  <Transition name="cmpui_modal_transition">
    <Teleport v-if="show" to="body">
      <div
        ref="el"
        class="cmpui_modal__overlay"
        aria-modal="true"
        :aria-labelledby="id"
        @keydown.esc="emit('close')"
      >
        <div role="dialog" class="cmpui_float-box__root cmpui_modal__root">
          <div class="cmpui_modal__header">
            <div :id="id" class="cmpui_modal__title">{{ title }}</div>
            <IconButton
              class="cmpui_modal__close-button"
              size="S"
              @click="emit('close')"
            >
            </IconButton>
          </div>
          <slot></slot>
        </div>
      </div>
    </Teleport>
  </Transition>
</template>
